source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'devops-ios-demo' do

platform:ios, '8.0'

pod 'AlicloudUpdate',      '1.0.0.5'

end


#post_install do |installer|
#    installer.generated_projects.each do |project|
#        project.targets.each do |target|
#            target.build_configurations.each do |config|
#                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#            end
#        end
#    end
#end
