# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/aliyun/aliyun-specs.git'

target 'mac_v2_ios_demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mac_v2_ios_demo
  pod 'AlicloudMAC', '~> 1.0.0'

end
