platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'crash_ios_demo' do
  use_frameworks!

  pod 'AlicloudApmCrashAnalysis' , '~> 0.0.1'

end