source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'httpdns_ios_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AlicloudHTTPDNS', '3.4.0'
  pod 'EMASLocalProxy', '1.3.6'
  pod 'EMASCurl', '1.5.2'

  pod 'AFNetworking'
  pod 'Alamofire'
  pod 'SDWebImage'

  # Pods for httpdns_ios_demo

  target 'httpdns_ios_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'httpdns_ios_demoUITests' do
    # Pods for testing
  end

end
