source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'httpdns_ios_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AlicloudHTTPDNS'

  pod 'AFNetworking'
  pod 'Alamofire'
  pod 'SDWebImage'

  # Pods for httpdns_ios_demo

  target 'httpdns_ios_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'httpdns_ios_demoUITests' do
    # Pods for testing
  end

end
