# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'man_ios_demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for man_ios_demo

  pod 'AlicloudMAN', '1.0.13'

  target 'man_ios_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
