source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '12.0'

target 'apm_ios_demo' do
  use_frameworks!

  pod 'AlicloudApmAll' , '2.1.8', :subspecs => [
    'AlicloudApmMemAlloc',
    'AlicloudApmMemLeak',
    'AlicloudApmRemoteLog',
  ]

end
