# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#
#ali_source 'alibaba-specs-mirror'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'hotfix-ios-demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hotfix-ios-demo

  #pod "AlicloudHotFix", "~> 1.0.0"
  #pod "AlicloudHotFixDebug", "~> 1.0.0"
  pod 'AlicloudLua'
  pod 'AlicloudBeacon'
  pod 'AlicloudUtils'
  pod 'AlicloudHotFixDebug'
  pod "ZipArchive", "~> 1.4"

end

#针对问题的解决方案：SDK does not contain 'libarclite' at the path 'xxx'; try increasing the minimum deployment target
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
