# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'mpush_ios_demo' do

pod 'AlicloudPush'

end

#Build_Env 1日常， 2预发， 3线上
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        puts "target name #{target.name}"
        if target.name == 'AlicloudPush'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','Build_Env=2']
            end
        end
    end
end

target 'mpush_service_extension' do

end

target 'mpush_content_extension' do

end

